apiVersion: v1
kind: Namespace
metadata:
  name: jitsi
  labels:
    name: jitsi
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: jitsi
  name: jitsi-config
data:
  TZ: America/Los_Angeles 
  XMPP_SERVER: littledarling.org.uk 
  PUBLIC_URL: https://littledarling.org.uk 
  XMPP_BOSH_URL_BASE: http://littledarling.org.uk:5280 
  DOCKER_HOST_ADDRESS: littledarling.org.uk 
  JICOFO_COMPONENT_SECRET: SGVsbG9AMTIzNDU25467gfh 
  JVB_AUTH_PASSWORD: SGVsbG9AMTIzNDU25467gfh 
  JICOFO_AUTH_PASSWORD: SGVsbG9AMTIzNDU25467gfh 
  JWT_APP_ID: 7982734743267 
  JWT_APP_SECRET: SGVsbG9AMTIzNDU25467gfh
  JWT_ACCEPTED_ISSUERS: my_web_client,my_app_client