apiVersion: v1
kind: Namespace
metadata:
  name: jitsi
  labels:
    name: jitsi
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: jitsi
  name: jitsi-config
data:
  TZ: America/Los_Angeles 
  XMPP_SERVER: a9034c78bf329456cbdc6b7001a51439-1773099539.ap-south-1.elb.amazonaws.com 
  PUBLIC_URL: http://a9034c78bf329456cbdc6b7001a51439-1773099539.ap-south-1.elb.amazonaws.com 
  XMPP_BOSH_URL_BASE: http://a9034c78bf329456cbdc6b7001a51439-1773099539.ap-south-1.elb.amazonaws.com:5280 
  DOCKER_HOST_ADDRESS: a9034c78bf329456cbdc6b7001a51439-1773099539.ap-south-1.elb.amazonaws.com 
  JICOFO_COMPONENT_SECRET: SGVsbG9AMTIzNDU25467gfh 
  JVB_AUTH_PASSWORD: SGVsbG9AMTIzNDU25467gfh 
  JICOFO_AUTH_PASSWORD: SGVsbG9AMTIzNDU25467gfh 
  JWT_APP_ID: GWR 
  JWT_APP_SECRET: SGVsbG9AMTIzNDU25467gfh
  JWT_ACCEPTED_ISSUERS: my_web_client,my_app_client